topic_hz_checker:
  ros__parameters:
    hardware_id: cub3
    update_period: 1.0
    topics:
      fix:
        topic: "/fix"
        type: "sensor_msgs/msg/NavSatFix"
        expected_hz: 1.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100
      imu:
        topic: "/imu/data"
        type: "sensor_msgs/msg/Imu"
        expected_hz: 386.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 1000
      odom:
        topic: "/odom"
        type: "nav_msgs/msg/Odometry"
        expected_hz: 20.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100
      realsense:
        topic: "/camera/camera/color/camera_info"
        type: "sensor_msgs/msg/CameraInfo"
        expected_hz: 30.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100
      sllidar_l:
        topic: "/SLC1L_scan"
        type: "sensor_msgs/msg/LaserScan"
        expected_hz: 10.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100
      sllidar_r:
        topic: "/SLC1R_scan"
        type: "sensor_msgs/msg/LaserScan"
        expected_hz: 10.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100
      velodyne:
        topic: "/velodyne_points"
        type: "sensor_msgs/msg/PointCloud2"
        expected_hz: 10.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: reliable
          durability: volatile
          depth: 100
      wheel_positions:
        topic: "/wheel_positions"
        type: "std_msgs/msg/Int32MultiArray"
        expected_hz: 20.0
        tolerance: 0.2
        window_size: 10
        qos:
          reliability: best_effort
          durability: volatile
          depth: 100

linux_state:
  ros__parameters:
    hardware_id: cub3
    update_period: 1.0
    cpu:
      warn: 0.8
      error: 0.9
    memory:
      warn: 0.8
      error: 0.9
    swap:
      warn: 0.5
      error: 0.8
    storage:
      paths: ["/"]
      warn: 0.8
      error: 0.9
jetson_state:
  ros__parameters:
    hardware_id: cub3
    update_period: 1.0
    thermal_zones:
      - "cpu-thermal"
      - "gpu-thermal"
      - "soc0-thermal"
      - "soc1-thermal"
      - "soc2-thermal"
      - "tj-thermal"
    warn_temperature: 65.0
    error_temperature: 80.0
diagnostic_aggregator:
  ros__parameters:
    pub_rate: 1.0
    analyzers:
      system:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Robot
        analyzers:
          sensors:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Sensors
            contains: [
              "TopicMonitor",
              "velodyne_points",
              "velodyne_packets",
              # "fix", # これだとfix topic statusも含まれてしまう
            ]
            regex: [
              "^ublox_gps_node: fix$" # これならfixだけ取れる
            ]
          linux:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Linux
            contains: [
              # "Joystick Driver Status", #繋がってない間Errorになるので外してる
              "Linux CPU Usage",
              "Linux Memory Usage",
              "Linux Swap Usage",
              "Linux Storage Usage",
              "Jetson Thermal State"
            ]
