/lidar_imu:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 2000
/lidar_points:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 100
/camera_node/image_raw/compressed:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 100
/camera_node/image_raw:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 100
