# waypoints list
waypoints_list:
    - id: 0
      x: 20.00
      y: 20.00

    - id: 1
      x: 21.40
      y: 20.00

    - id: 2
      x: 21.40
      y: 23.36

    - id: 3
      x: 20.00
      y: 23.36

    - id: 4
      x: 18.60
      y: 23.36

    - id: 5
      x: 18.60
      y: 20.00

    - id: 6
      x: 18.60
      y: 16.60

    - id: 7
      x: 20.00
      y: 16.60

    - id: 8
      x: 21.40
      y: 16.60

    - id: 9
      x: 21.40
      y: 20.00
