ekf_se_odom:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    imu0: /BNO055/imu
    imu0_config: [false, false, false,
                  true, true, false,
                  false, false, false,
                  true, true, false,
                  false, false, false]
    imu0_queue_size: 5
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
