/**:
  ros__parameters:
    common:
      img_topic: "/camera/image_raw"
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false

    extrin_calib:
      extrinsic_T: [0.04165, 0.02326, -0.0284]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      Rcl: [-0.01364, -0.99983,  -0.01237,
            0.50127, 0.00387, -0.86528,
            0.86518, -0.01801,0.50113]
      Pcl: [0.00901, 0.01036, -0.06285]

    time_offset: 
      imu_time_offset: 0.0
      img_time_offset: 0.1
      exposure_time_init: 0.0

    preprocess:
      point_filter_num: 1
      filter_size_surf: 0.1
      lidar_type: 7 # Livox MID360 LiDAR ros/FAST-LIVO2-ROS2-MID360-Fisheye/include/common_lib.h
      scan_line: 4
      blind: 0.5

    vio:
      max_iterations: 5
      outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
      img_point_cov: 100 # 100 1000 
      patch_size: 8
      patch_pyrimid_level: 4
      normal_en: true
      raycast_en: false
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 30
      acc_cov: 0.8 #0.5 # 0.2
      gyr_cov: 0.3 # 0.5
      b_acc_cov: 0.0001 # 0.1
      b_gyr_cov: 0.0001 # 0.1

    lio:
      max_iterations: 5
      dept_err: 0.02
      beam_err: 0.05
      min_eigen_value: 0.005 #0.0025 # 0.005
      voxel_size: 0.5
      max_layer: 2
      max_points_num: 50
      layer_init_num: [5, 5, 5, 5, 5]

    local_map:  
      map_sliding_en: false
      half_map_size: 100
      sliding_thresh: 8.0

    uav:
      imu_rate_odom: false
      gravity_align_en: true

    publish:
      dense_map_en: true
      pub_effect_point_en: false 
      pub_plane_en: false
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "CBD_Building_01"
      pose_output_en: false

    pcd_save:
      pcd_save_en: true
      colmap_output_en: true # need to set interval = -1
      filter_size_pcd: 0.15
      interval: -1
      # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
