/livox/imu:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 2000
/livox/lidar:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 100
/camera/image_raw/compressed:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 100
