# ここにNVIDIAコンテナが可能な場合の設定を書く
# docker_util.sh でマージして使う

services:
  cub_ros:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  cub_ros_vnc:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
